import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:tasks_app/features/auth/application/auth_providers.dart';

import 'routes.dart';

// appRoutes is generated by go_router_generator
//and used to define the routes in the GoRouter instance.
// we use provider state because the value of the router is ready and should not 
//  be changed after the app is initialized.
final routerProvider = Provider<GoRouter>((ref) {
  final authState = ref.watch(authStateProvider);
  debugPrint("this is the current users ${authState.asData}",);

  return GoRouter(
    routes: $appRoutes,
    redirect: (context, state) {
      final location = state.matchedLocation;
      final isLoadingRoute = location == '/auth/loading';
      final isPublicAuthRoute =
          location == '/sign-in' || location == '/sign-up' || location == '/';

      if (authState.isLoading) {
        // if authState.isLoading True we return nothing | else we 
        // are not in the loading route and we the authState is still loading we 
        // redirect to the /auth/loading
        return isLoadingRoute ? null : '/auth/loading';
      }

      final isSignedIn = authState.when(
        data: (user) => user != null,
        loading: () => false,
        error: (_, _) => false,
      );

     

      if (!isSignedIn) {
        // if it is a public auth route, we don't need to redirect
        // if it is not a public auth route, we redirect to sign-in
        return isPublicAuthRoute ? null : '/';
      }
    // if user is Sign in 
      if (isLoadingRoute || isPublicAuthRoute) return '/tasks';
      return null;
    },
  );
});
